name: green_pedals
description: An eco-friendly cycle share system

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  splashscreen: ^1.3.5
  flutter_svg: ^0.17.4
  qrscan: ^0.2.22
  image_gallery_saver: ^1.1.0
  image_picker: ^0.8.0+3
  permission_handler: ^8.1.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
